### ISSUE TITLE
`signal_state()` is quite slow

### ISSUE THREAD

**Issue by mgirlich** [r-lib/lifecycle#167]
As it is used for superseded functions this isn't very nice.

```r
f <- function() {
  lifecycle::signal_stage("superseded", "recode()", "case_match()")
}

for (i in 1:1000) {
  f()
}
```

<img width="856" alt="image" src="https://github.com/r-lib/lifecycle/assets/18258854/4f285adb-14d0-41d9-b718-f59e8719a0e3">

E.g. this made `dplyr::recode()` so much slower than before.

**Comment by DavisVaughan** [comment]
Not really sure the `readCitationFile` part is "real" here. signaling is definitely slow though, and has been a reoccurring issue

```
library(lifecycle)
xx <- profvis::profvis(for (i in 1:1000) signal_stage("superseded", "recode()", "case_match()"))
print(xx, aggregate = T)
```
<img width="1291" alt="Screenshot 2023-07-12 at 8 57 13 AM" src="https://github.com/r-lib/lifecycle/assets/19150088/8818b135-f876-4166-9a85-d064547a0538">

**Comment by DavisVaughan** [comment]
See also https://github.com/r-lib/rlang/issues/1609 for `.rlang_cli_compat()` being slow

**Comment by DavisVaughan** [comment]
I think I've looked at `isatty()` before too and I couldn't ever figure out why it was slow. It is so fast on its own

``` r
bench::mark(isatty(stdout()))
#> # A tibble: 1 × 6
#>   expression            min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 isatty(stdout())    246ns    328ns  2223575.        0B        0
```

<sup>Created on 2023-07-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
Oh but the `get_data()` call _is_ particularly slow _when called from RStudio_. i.e. if you run this in a reprex in a separate session it is very fast, but interactively in RStudio it is slow:

```r
> bench::mark(cli:::rstudio$.internal$get_data())
# A tibble: 1 × 13
  expression           min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result      
  <bch:expr>         <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>      
1 cli:::rstudio$.in… 787µs  809µs     1161.    41.1KB     17.3   538     8      463ms <named list>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
```

800us * 100 = 800ms which roughly aligns with my profvis result

It looks like most of the time is in the rstudioapi function calls

```r
> bench::mark(asNamespace("rstudioapi")$isAvailable())
# A tibble: 1 × 13
  expression      min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result memory    
  <bch:expr>   <bch:> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list> <list>    
1 "asNamespac… 1.11µs 1.31µs   700181.        0B     70.0  9999     1     14.3ms <lgl>  <Rprofmem>
# ℹ 2 more variables: time <list>, gc <list>

> bench::mark(asNamespace("rstudioapi")$getVersion())
# A tibble: 1 × 13
  expression             min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result    
  <bch:expr>           <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>    
1 "asNamespace(\"rstu… 384µs  403µs     2414.    20.6KB     17.2  1125     8      466ms <pckg_vrs>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>

> bench::mark(asNamespace("rstudioapi")$versionInfo()$mode)
# A tibble: 1 × 13
  expression      min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result memory    
  <bch:expr>    <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list> <list>    
1 "asNamespace… 382µs  396µs     2460.    20.6KB     17.2  1147     8      466ms <chr>  <Rprofmem>
# ℹ 2 more variables: time <list>, gc <list>
```

CC @gaborcsardi

**Comment by DavisVaughan** [comment]
Another option is to make `rlang:::has_ansi()` cache its result so it doesn't have to keep calling cli

**Comment by DavisVaughan** [comment]
It looks like rstudioapi's `versionInfo()` is actually the one calling `readCitationFile()`!

```r
xx <- profvis::profvis(for (i in 1:1000) asNamespace("rstudioapi")$callFun("versionInfo"))
print(xx, aggregate = TRUE)
```
<img width="1008" alt="Screenshot 2023-07-12 at 9 17 28 AM" src="https://github.com/r-lib/lifecycle/assets/19150088/6c7c6787-acf2-4070-b751-0d203c715f71">



```r
> asNamespace("rstudioapi")$versionInfo()
$citation
To cite RStudio in publications use:

  Posit team (2023). RStudio: Integrated Development Environment for R. Posit Software,
  PBC, Boston, MA. URL http://www.posit.co/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{Posit team}},
    organization = {Posit Software, PBC},
    address = {Boston, MA},
    year = {2023},
    url = {http://www.posit.co/},
  }

$mode
[1] "desktop"

$version
[1] ‘2023.6.0.421’

$long_version
[1] "2023.06.0+421"

$release_name
[1] "Mountain Hydrangea"
```

This is used by cli when getting the version number and the mode
https://github.com/r-lib/cli/blob/7eb56ebc4c315ecfef74148881b15a522c8946bf/R/aab-rstudio-detect.R#L35-L36

One step cli could take is to just make one call to `versionInfo()`, because that has the version in it as `versionInfo()$version`, so there is no need to also call `$getVersion()`.

But I think a much better solution would be:
- Make `rstudioapi::getVersion()` not rely on `rstudioapi::versionInfo()`, so it doesn't pay the cost of the citation file
- Add `rstudioapi::getMode()` which just returns the `$mode` of `versionInfo()`

**Comment by DavisVaughan** [comment]
I've broken this down to 4 individual fixes
- [ ] `rstudioapi::getVersion()` can easily be much faster https://github.com/rstudio/rstudioapi/issues/279
- [ ] `rstudioapi::getMode()` should exist https://github.com/rstudio/rstudioapi/issues/280
- [ ] cli should use `getMode()` over `versionInfo()$mode` https://github.com/r-lib/cli/issues/621
- [ ] rlang should cache its own version to avoid `packageVersion()` calls https://github.com/r-lib/rlang/issues/1609

**Comment by DavisVaughan** [comment]
Yea I quickly mentioned that here https://github.com/r-lib/lifecycle/issues/167#issuecomment-1632504106. I do think that would be a good quick solution

**Comment by gaborcsardi** [comment]
> It won't be dynamic to any options like "crayon.enabled" anymore, but maybe that is ok, not sure

I an not sure what you mean.

**Comment by DavisVaughan** [comment]
- Call `has_ansi()`, it reports `TRUE` because `cli::num_ansi_colors() > 1` is `TRUE`
- Set `options(crayon.enabled = FALSE)`
- Call `has_ansi()` again. It's cached so it reports `TRUE` again even though in theory if it wasn't cached it would report `FALSE`

i.e. here is what happens today without caching, which would no longer be true with caching

```r
> rlang:::has_ansi()
[1] TRUE
> options(crayon.enabled = F)
> rlang:::has_ansi()
[1] FALSE
```

**Comment by gaborcsardi** [comment]
You would cache in the function that make a lot of calls downstream. E.g. if one function calls cli many times then there. If another function calls the first function many times, then there. 

If there is such a function, and this is not about speeding up a single call...

**Comment by hadley** [comment]
I think we can get a big improvement here from switching from `expr_deparse()` to `deparse()`, because then we avoid the colour checking path all together.

**Comment by hadley** [comment]
There was a  ~6x performance improvement in #172, by removing the most obvious bottleneck. We'll make it faster in the future by doing more work lazily, which is tracked in #176.
